// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/internal/steps (interfaces: FileWriter)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/file_writer_mock.go . FileWriter
//

// Package mock_steps is a generated GoMock package.
package mock_steps

import (
	fs "io/fs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileWriter is a mock of FileWriter interface.
type MockFileWriter struct {
	ctrl     *gomock.Controller
	recorder *MockFileWriterMockRecorder
	isgomock struct{}
}

// MockFileWriterMockRecorder is the mock recorder for MockFileWriter.
type MockFileWriterMockRecorder struct {
	mock *MockFileWriter
}

// NewMockFileWriter creates a new mock instance.
func NewMockFileWriter(ctrl *gomock.Controller) *MockFileWriter {
	mock := &MockFileWriter{ctrl: ctrl}
	mock.recorder = &MockFileWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileWriter) EXPECT() *MockFileWriterMockRecorder {
	return m.recorder
}

// WriteFile mocks base method.
func (m *MockFileWriter) WriteFile(name string, data []byte, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFileWriterMockRecorder) WriteFile(name, data, perm any) *MockFileWriterWriteFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFileWriter)(nil).WriteFile), name, data, perm)
	return &MockFileWriterWriteFileCall{Call: call}
}

// MockFileWriterWriteFileCall wrap *gomock.Call
type MockFileWriterWriteFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileWriterWriteFileCall) Return(arg0 error) *MockFileWriterWriteFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileWriterWriteFileCall) Do(f func(string, []byte, fs.FileMode) error) *MockFileWriterWriteFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileWriterWriteFileCall) DoAndReturn(f func(string, []byte, fs.FileMode) error) *MockFileWriterWriteFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
