// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/internal/steps (interfaces: StepCreateVirtualMachineDriver)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/step_create_virtual_machine_driver_mock.go . StepCreateVirtualMachineDriver
//

// Package mock_steps is a generated GoMock package.
package mock_steps

import (
	context "context"
	reflect "reflect"

	driver "github.com/mws-cloud-platform/packer-plugin-mws/internal/driver"
	ipaddress "go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"
	bytesize "go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"
	compute "go.mws.cloud/go-sdk/service/resources/references/compute"
	gomock "go.uber.org/mock/gomock"
)

// MockStepCreateVirtualMachineDriver is a mock of StepCreateVirtualMachineDriver interface.
type MockStepCreateVirtualMachineDriver struct {
	ctrl     *gomock.Controller
	recorder *MockStepCreateVirtualMachineDriverMockRecorder
	isgomock struct{}
}

// MockStepCreateVirtualMachineDriverMockRecorder is the mock recorder for MockStepCreateVirtualMachineDriver.
type MockStepCreateVirtualMachineDriverMockRecorder struct {
	mock *MockStepCreateVirtualMachineDriver
}

// NewMockStepCreateVirtualMachineDriver creates a new mock instance.
func NewMockStepCreateVirtualMachineDriver(ctrl *gomock.Controller) *MockStepCreateVirtualMachineDriver {
	mock := &MockStepCreateVirtualMachineDriver{ctrl: ctrl}
	mock.recorder = &MockStepCreateVirtualMachineDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepCreateVirtualMachineDriver) EXPECT() *MockStepCreateVirtualMachineDriverMockRecorder {
	return m.recorder
}

// AttachDiskToVirtualMachine mocks base method.
func (m *MockStepCreateVirtualMachineDriver) AttachDiskToVirtualMachine(arg0 context.Context, arg1 string, arg2 *compute.DiskRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachDiskToVirtualMachine", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachDiskToVirtualMachine indicates an expected call of AttachDiskToVirtualMachine.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) AttachDiskToVirtualMachine(arg0, arg1, arg2 any) *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachDiskToVirtualMachine", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).AttachDiskToVirtualMachine), arg0, arg1, arg2)
	return &MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall{Call: call}
}

// MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall) Do(f func(context.Context, string, *compute.DiskRef) error) *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall) DoAndReturn(f func(context.Context, string, *compute.DiskRef) error) *MockStepCreateVirtualMachineDriverAttachDiskToVirtualMachineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateDisk mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateDisk(arg0 context.Context, arg1 driver.CreateDiskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDisk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDisk indicates an expected call of CreateDisk.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateDisk(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateDiskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDisk", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateDisk), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateDiskCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateDiskCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateDiskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateDiskCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverCreateDiskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateDiskCall) Do(f func(context.Context, driver.CreateDiskParams) error) *MockStepCreateVirtualMachineDriverCreateDiskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateDiskCall) DoAndReturn(f func(context.Context, driver.CreateDiskParams) error) *MockStepCreateVirtualMachineDriverCreateDiskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateExternalAddress mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateExternalAddress(arg0 context.Context, arg1 driver.CreateExternalAddressParams) (*ipaddress.IPAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExternalAddress", arg0, arg1)
	ret0, _ := ret[0].(*ipaddress.IPAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternalAddress indicates an expected call of CreateExternalAddress.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateExternalAddress(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateExternalAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalAddress", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateExternalAddress), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateExternalAddressCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateExternalAddressCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateExternalAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateExternalAddressCall) Return(arg0 *ipaddress.IPAddress, arg1 error) *MockStepCreateVirtualMachineDriverCreateExternalAddressCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateExternalAddressCall) Do(f func(context.Context, driver.CreateExternalAddressParams) (*ipaddress.IPAddress, error)) *MockStepCreateVirtualMachineDriverCreateExternalAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateExternalAddressCall) DoAndReturn(f func(context.Context, driver.CreateExternalAddressParams) (*ipaddress.IPAddress, error)) *MockStepCreateVirtualMachineDriverCreateExternalAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateFirewallRule mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateFirewallRule(arg0 context.Context, arg1 driver.CreateFirewallRuleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFirewallRule", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFirewallRule indicates an expected call of CreateFirewallRule.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateFirewallRule(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFirewallRule", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateFirewallRule), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateFirewallRuleCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateFirewallRuleCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateFirewallRuleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall) Do(f func(context.Context, driver.CreateFirewallRuleParams) error) *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall) DoAndReturn(f func(context.Context, driver.CreateFirewallRuleParams) error) *MockStepCreateVirtualMachineDriverCreateFirewallRuleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateNetwork mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateNetwork(arg0 context.Context, arg1 driver.CreateNetworkParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateNetwork(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateNetwork), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateNetworkCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateNetworkCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateNetworkCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverCreateNetworkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateNetworkCall) Do(f func(context.Context, driver.CreateNetworkParams) error) *MockStepCreateVirtualMachineDriverCreateNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateNetworkCall) DoAndReturn(f func(context.Context, driver.CreateNetworkParams) error) *MockStepCreateVirtualMachineDriverCreateNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSubnet mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateSubnet(arg0 context.Context, arg1 driver.CreateSubnetParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateSubnet(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateSubnetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateSubnet), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateSubnetCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateSubnetCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateSubnetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateSubnetCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverCreateSubnetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateSubnetCall) Do(f func(context.Context, driver.CreateSubnetParams) error) *MockStepCreateVirtualMachineDriverCreateSubnetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateSubnetCall) DoAndReturn(f func(context.Context, driver.CreateSubnetParams) error) *MockStepCreateVirtualMachineDriverCreateSubnetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateVirtualMachine mocks base method.
func (m *MockStepCreateVirtualMachineDriver) CreateVirtualMachine(arg0 context.Context, arg1 driver.CreateVirtualMachineParams) (*ipaddress.IPAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*ipaddress.IPAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVirtualMachine indicates an expected call of CreateVirtualMachine.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) CreateVirtualMachine(arg0, arg1 any) *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVirtualMachine", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).CreateVirtualMachine), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverCreateVirtualMachineCall{Call: call}
}

// MockStepCreateVirtualMachineDriverCreateVirtualMachineCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverCreateVirtualMachineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall) Return(arg0 *ipaddress.IPAddress, arg1 error) *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall) Do(f func(context.Context, driver.CreateVirtualMachineParams) (*ipaddress.IPAddress, error)) *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall) DoAndReturn(f func(context.Context, driver.CreateVirtualMachineParams) (*ipaddress.IPAddress, error)) *MockStepCreateVirtualMachineDriverCreateVirtualMachineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteDisk mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteDisk(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDisk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDisk indicates an expected call of DeleteDisk.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteDisk(arg0, arg1 any) *MockStepCreateVirtualMachineDriverDeleteDiskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDisk", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteDisk), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverDeleteDiskCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteDiskCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteDiskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteDiskCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteDiskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteDiskCall) Do(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteDiskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteDiskCall) DoAndReturn(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteDiskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExternalAddress mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteExternalAddress(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalAddress", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalAddress indicates an expected call of DeleteExternalAddress.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteExternalAddress(arg0, arg1 any) *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalAddress", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteExternalAddress), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverDeleteExternalAddressCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteExternalAddressCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteExternalAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall) Do(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall) DoAndReturn(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteExternalAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteFirewallRule mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteFirewallRule(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFirewallRule", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFirewallRule indicates an expected call of DeleteFirewallRule.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteFirewallRule(arg0, arg1, arg2 any) *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewallRule", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteFirewallRule), arg0, arg1, arg2)
	return &MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall) Do(f func(context.Context, string, string) error) *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall) DoAndReturn(f func(context.Context, string, string) error) *MockStepCreateVirtualMachineDriverDeleteFirewallRuleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteNetwork mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteNetwork(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteNetwork(arg0, arg1 any) *MockStepCreateVirtualMachineDriverDeleteNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteNetwork), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverDeleteNetworkCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteNetworkCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteNetworkCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteNetworkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteNetworkCall) Do(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteNetworkCall) DoAndReturn(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSubnet mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteSubnet(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnet", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnet indicates an expected call of DeleteSubnet.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteSubnet(arg0, arg1, arg2 any) *MockStepCreateVirtualMachineDriverDeleteSubnetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnet", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteSubnet), arg0, arg1, arg2)
	return &MockStepCreateVirtualMachineDriverDeleteSubnetCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteSubnetCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteSubnetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteSubnetCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteSubnetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteSubnetCall) Do(f func(context.Context, string, string) error) *MockStepCreateVirtualMachineDriverDeleteSubnetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteSubnetCall) DoAndReturn(f func(context.Context, string, string) error) *MockStepCreateVirtualMachineDriverDeleteSubnetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteVirtualMachine mocks base method.
func (m *MockStepCreateVirtualMachineDriver) DeleteVirtualMachine(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVirtualMachine indicates an expected call of DeleteVirtualMachine.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) DeleteVirtualMachine(arg0, arg1 any) *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVirtualMachine", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).DeleteVirtualMachine), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall{Call: call}
}

// MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall) Return(arg0 error) *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall) Do(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall) DoAndReturn(f func(context.Context, string) error) *MockStepCreateVirtualMachineDriverDeleteVirtualMachineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDiskBackupMinDiskSize mocks base method.
func (m *MockStepCreateVirtualMachineDriver) GetDiskBackupMinDiskSize(arg0 context.Context, arg1 *compute.DiskBackupRef) (*bytesize.ByteSize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiskBackupMinDiskSize", arg0, arg1)
	ret0, _ := ret[0].(*bytesize.ByteSize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiskBackupMinDiskSize indicates an expected call of GetDiskBackupMinDiskSize.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) GetDiskBackupMinDiskSize(arg0, arg1 any) *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiskBackupMinDiskSize", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).GetDiskBackupMinDiskSize), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall{Call: call}
}

// MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall) Return(arg0 *bytesize.ByteSize, arg1 error) *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall) Do(f func(context.Context, *compute.DiskBackupRef) (*bytesize.ByteSize, error)) *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall) DoAndReturn(f func(context.Context, *compute.DiskBackupRef) (*bytesize.ByteSize, error)) *MockStepCreateVirtualMachineDriverGetDiskBackupMinDiskSizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetImageMinDiskSize mocks base method.
func (m *MockStepCreateVirtualMachineDriver) GetImageMinDiskSize(arg0 context.Context, arg1 *compute.ImageRef) (*bytesize.ByteSize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageMinDiskSize", arg0, arg1)
	ret0, _ := ret[0].(*bytesize.ByteSize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageMinDiskSize indicates an expected call of GetImageMinDiskSize.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) GetImageMinDiskSize(arg0, arg1 any) *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageMinDiskSize", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).GetImageMinDiskSize), arg0, arg1)
	return &MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall{Call: call}
}

// MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall) Return(arg0 *bytesize.ByteSize, arg1 error) *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall) Do(f func(context.Context, *compute.ImageRef) (*bytesize.ByteSize, error)) *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall) DoAndReturn(f func(context.Context, *compute.ImageRef) (*bytesize.ByteSize, error)) *MockStepCreateVirtualMachineDriverGetImageMinDiskSizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSerialPortOutput mocks base method.
func (m *MockStepCreateVirtualMachineDriver) GetSerialPortOutput(arg0 context.Context, arg1 string, arg2 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerialPortOutput", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSerialPortOutput indicates an expected call of GetSerialPortOutput.
func (mr *MockStepCreateVirtualMachineDriverMockRecorder) GetSerialPortOutput(arg0, arg1, arg2 any) *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSerialPortOutput", reflect.TypeOf((*MockStepCreateVirtualMachineDriver)(nil).GetSerialPortOutput), arg0, arg1, arg2)
	return &MockStepCreateVirtualMachineDriverGetSerialPortOutputCall{Call: call}
}

// MockStepCreateVirtualMachineDriverGetSerialPortOutputCall wrap *gomock.Call
type MockStepCreateVirtualMachineDriverGetSerialPortOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall) Return(arg0 []byte, arg1 error) *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall) Do(f func(context.Context, string, int) ([]byte, error)) *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall) DoAndReturn(f func(context.Context, string, int) ([]byte, error)) *MockStepCreateVirtualMachineDriverGetSerialPortOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
