// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/internal/steps (interfaces: StepCreateHMACKeyDriver)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/step_create_hmac_key_driver_mock.go . StepCreateHMACKeyDriver
//

// Package mock_steps is a generated GoMock package.
package mock_steps

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStepCreateHMACKeyDriver is a mock of StepCreateHMACKeyDriver interface.
type MockStepCreateHMACKeyDriver struct {
	ctrl     *gomock.Controller
	recorder *MockStepCreateHMACKeyDriverMockRecorder
	isgomock struct{}
}

// MockStepCreateHMACKeyDriverMockRecorder is the mock recorder for MockStepCreateHMACKeyDriver.
type MockStepCreateHMACKeyDriverMockRecorder struct {
	mock *MockStepCreateHMACKeyDriver
}

// NewMockStepCreateHMACKeyDriver creates a new mock instance.
func NewMockStepCreateHMACKeyDriver(ctrl *gomock.Controller) *MockStepCreateHMACKeyDriver {
	mock := &MockStepCreateHMACKeyDriver{ctrl: ctrl}
	mock.recorder = &MockStepCreateHMACKeyDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepCreateHMACKeyDriver) EXPECT() *MockStepCreateHMACKeyDriverMockRecorder {
	return m.recorder
}

// CreateHMACKey mocks base method.
func (m *MockStepCreateHMACKeyDriver) CreateHMACKey(ctx context.Context, serviceAccount, name string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHMACKey", ctx, serviceAccount, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateHMACKey indicates an expected call of CreateHMACKey.
func (mr *MockStepCreateHMACKeyDriverMockRecorder) CreateHMACKey(ctx, serviceAccount, name any) *MockStepCreateHMACKeyDriverCreateHMACKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHMACKey", reflect.TypeOf((*MockStepCreateHMACKeyDriver)(nil).CreateHMACKey), ctx, serviceAccount, name)
	return &MockStepCreateHMACKeyDriverCreateHMACKeyCall{Call: call}
}

// MockStepCreateHMACKeyDriverCreateHMACKeyCall wrap *gomock.Call
type MockStepCreateHMACKeyDriverCreateHMACKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateHMACKeyDriverCreateHMACKeyCall) Return(accessKey, secretKey string, err error) *MockStepCreateHMACKeyDriverCreateHMACKeyCall {
	c.Call = c.Call.Return(accessKey, secretKey, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateHMACKeyDriverCreateHMACKeyCall) Do(f func(context.Context, string, string) (string, string, error)) *MockStepCreateHMACKeyDriverCreateHMACKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateHMACKeyDriverCreateHMACKeyCall) DoAndReturn(f func(context.Context, string, string) (string, string, error)) *MockStepCreateHMACKeyDriverCreateHMACKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteHMACKey mocks base method.
func (m *MockStepCreateHMACKeyDriver) DeleteHMACKey(ctx context.Context, serviceAccount, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHMACKey", ctx, serviceAccount, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHMACKey indicates an expected call of DeleteHMACKey.
func (mr *MockStepCreateHMACKeyDriverMockRecorder) DeleteHMACKey(ctx, serviceAccount, name any) *MockStepCreateHMACKeyDriverDeleteHMACKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHMACKey", reflect.TypeOf((*MockStepCreateHMACKeyDriver)(nil).DeleteHMACKey), ctx, serviceAccount, name)
	return &MockStepCreateHMACKeyDriverDeleteHMACKeyCall{Call: call}
}

// MockStepCreateHMACKeyDriverDeleteHMACKeyCall wrap *gomock.Call
type MockStepCreateHMACKeyDriverDeleteHMACKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepCreateHMACKeyDriverDeleteHMACKeyCall) Return(arg0 error) *MockStepCreateHMACKeyDriverDeleteHMACKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepCreateHMACKeyDriverDeleteHMACKeyCall) Do(f func(context.Context, string, string) error) *MockStepCreateHMACKeyDriverDeleteHMACKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepCreateHMACKeyDriverDeleteHMACKeyCall) DoAndReturn(f func(context.Context, string, string) error) *MockStepCreateHMACKeyDriverDeleteHMACKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
