// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package mws

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatDiskConfig is an auto-generated flat version of DiskConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDiskConfig struct {
	DiskName       *string `mapstructure:"disk_name" required:"false" cty:"disk_name" hcl:"disk_name"`
	DiskType       *string `mapstructure:"disk_type" required:"false" cty:"disk_type" hcl:"disk_type"`
	DiskSize       *string `mapstructure:"disk_size" required:"false" cty:"disk_size" hcl:"disk_size"`
	DiskIOPS       *int64  `mapstructure:"disk_iops" required:"false" cty:"disk_iops" hcl:"disk_iops"`
	SourceProject  *string `mapstructure:"source_project" required:"false" cty:"source_project" hcl:"source_project"`
	SourceImage    *string `mapstructure:"source_image" required:"false" cty:"source_image" hcl:"source_image"`
	SourceSnapshot *string `mapstructure:"source_snapshot" required:"false" cty:"source_snapshot" hcl:"source_snapshot"`
}

// FlatMapstructure returns a new FlatDiskConfig.
// FlatDiskConfig is an auto-generated flat version of DiskConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DiskConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDiskConfig)
}

// HCL2Spec returns the hcl spec of a DiskConfig.
// This spec is used by HCL to read the fields of DiskConfig.
// The decoded values from this spec will then be applied to a FlatDiskConfig.
func (*FlatDiskConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"disk_name":       &hcldec.AttrSpec{Name: "disk_name", Type: cty.String, Required: false},
		"disk_type":       &hcldec.AttrSpec{Name: "disk_type", Type: cty.String, Required: false},
		"disk_size":       &hcldec.AttrSpec{Name: "disk_size", Type: cty.String, Required: false},
		"disk_iops":       &hcldec.AttrSpec{Name: "disk_iops", Type: cty.Number, Required: false},
		"source_project":  &hcldec.AttrSpec{Name: "source_project", Type: cty.String, Required: false},
		"source_image":    &hcldec.AttrSpec{Name: "source_image", Type: cty.String, Required: false},
		"source_snapshot": &hcldec.AttrSpec{Name: "source_snapshot", Type: cty.String, Required: false},
	}
	return s
}
