// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/post-processor/mws-import (interfaces: AWSClient)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/aws_mock.go . AWSClient
//

// Package mock_mwsimport is a generated GoMock package.
package mock_mwsimport

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockAWSClient is a mock of AWSClient interface.
type MockAWSClient struct {
	ctrl     *gomock.Controller
	recorder *MockAWSClientMockRecorder
	isgomock struct{}
}

// MockAWSClientMockRecorder is the mock recorder for MockAWSClient.
type MockAWSClientMockRecorder struct {
	mock *MockAWSClient
}

// NewMockAWSClient creates a new mock instance.
func NewMockAWSClient(ctrl *gomock.Controller) *MockAWSClient {
	mock := &MockAWSClient{ctrl: ctrl}
	mock.recorder = &MockAWSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSClient) EXPECT() *MockAWSClientMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockAWSClient) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockAWSClientMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *MockAWSClientPresignGetObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockAWSClient)(nil).PresignGetObject), varargs...)
	return &MockAWSClientPresignGetObjectCall{Call: call}
}

// MockAWSClientPresignGetObjectCall wrap *gomock.Call
type MockAWSClientPresignGetObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSClientPresignGetObjectCall) Return(arg0 *v4.PresignedHTTPRequest, arg1 error) *MockAWSClientPresignGetObjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSClientPresignGetObjectCall) Do(f func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockAWSClientPresignGetObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSClientPresignGetObjectCall) DoAndReturn(f func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockAWSClientPresignGetObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
