// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/post-processor/mws-import (interfaces: Driver)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/driver_mock.go . Driver
//

// Package mock_mwsimport is a generated GoMock package.
package mock_mwsimport

import (
	context "context"
	reflect "reflect"

	driver "github.com/mws-cloud-platform/packer-plugin-mws/internal/driver"
	model "go.mws.cloud/go-sdk/service/compute/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// DeleteImage mocks base method.
func (m *MockDriver) DeleteImage(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockDriverMockRecorder) DeleteImage(arg0, arg1 any) *MockDriverDeleteImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockDriver)(nil).DeleteImage), arg0, arg1)
	return &MockDriverDeleteImageCall{Call: call}
}

// MockDriverDeleteImageCall wrap *gomock.Call
type MockDriverDeleteImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDriverDeleteImageCall) Return(arg0 error) *MockDriverDeleteImageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDriverDeleteImageCall) Do(f func(context.Context, string) error) *MockDriverDeleteImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDriverDeleteImageCall) DoAndReturn(f func(context.Context, string) error) *MockDriverDeleteImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImportImage mocks base method.
func (m *MockDriver) ImportImage(arg0 context.Context, arg1 driver.ImportImageParams) (*model.ImageOptionalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportImage", arg0, arg1)
	ret0, _ := ret[0].(*model.ImageOptionalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportImage indicates an expected call of ImportImage.
func (mr *MockDriverMockRecorder) ImportImage(arg0, arg1 any) *MockDriverImportImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportImage", reflect.TypeOf((*MockDriver)(nil).ImportImage), arg0, arg1)
	return &MockDriverImportImageCall{Call: call}
}

// MockDriverImportImageCall wrap *gomock.Call
type MockDriverImportImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDriverImportImageCall) Return(arg0 *model.ImageOptionalResponse, arg1 error) *MockDriverImportImageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDriverImportImageCall) Do(f func(context.Context, driver.ImportImageParams) (*model.ImageOptionalResponse, error)) *MockDriverImportImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDriverImportImageCall) DoAndReturn(f func(context.Context, driver.ImportImageParams) (*model.ImageOptionalResponse, error)) *MockDriverImportImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
