// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hashicorp/packer-plugin-sdk/packer (interfaces: Communicator)
//
// Generated by this command:
//
//	mockgen -typed -package=mock -destination=mock/communicator_mock.go github.com/hashicorp/packer-plugin-sdk/packer Communicator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	os "os"
	reflect "reflect"

	packer "github.com/hashicorp/packer-plugin-sdk/packer"
	gomock "go.uber.org/mock/gomock"
)

// MockCommunicator is a mock of Communicator interface.
type MockCommunicator struct {
	ctrl     *gomock.Controller
	recorder *MockCommunicatorMockRecorder
	isgomock struct{}
}

// MockCommunicatorMockRecorder is the mock recorder for MockCommunicator.
type MockCommunicatorMockRecorder struct {
	mock *MockCommunicator
}

// NewMockCommunicator creates a new mock instance.
func NewMockCommunicator(ctrl *gomock.Controller) *MockCommunicator {
	mock := &MockCommunicator{ctrl: ctrl}
	mock.recorder = &MockCommunicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunicator) EXPECT() *MockCommunicatorMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockCommunicator) Download(arg0 string, arg1 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockCommunicatorMockRecorder) Download(arg0, arg1 any) *MockCommunicatorDownloadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockCommunicator)(nil).Download), arg0, arg1)
	return &MockCommunicatorDownloadCall{Call: call}
}

// MockCommunicatorDownloadCall wrap *gomock.Call
type MockCommunicatorDownloadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommunicatorDownloadCall) Return(arg0 error) *MockCommunicatorDownloadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommunicatorDownloadCall) Do(f func(string, io.Writer) error) *MockCommunicatorDownloadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommunicatorDownloadCall) DoAndReturn(f func(string, io.Writer) error) *MockCommunicatorDownloadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DownloadDir mocks base method.
func (m *MockCommunicator) DownloadDir(src, dst string, exclude []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadDir", src, dst, exclude)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadDir indicates an expected call of DownloadDir.
func (mr *MockCommunicatorMockRecorder) DownloadDir(src, dst, exclude any) *MockCommunicatorDownloadDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadDir", reflect.TypeOf((*MockCommunicator)(nil).DownloadDir), src, dst, exclude)
	return &MockCommunicatorDownloadDirCall{Call: call}
}

// MockCommunicatorDownloadDirCall wrap *gomock.Call
type MockCommunicatorDownloadDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommunicatorDownloadDirCall) Return(arg0 error) *MockCommunicatorDownloadDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommunicatorDownloadDirCall) Do(f func(string, string, []string) error) *MockCommunicatorDownloadDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommunicatorDownloadDirCall) DoAndReturn(f func(string, string, []string) error) *MockCommunicatorDownloadDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockCommunicator) Start(arg0 context.Context, arg1 *packer.RemoteCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCommunicatorMockRecorder) Start(arg0, arg1 any) *MockCommunicatorStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommunicator)(nil).Start), arg0, arg1)
	return &MockCommunicatorStartCall{Call: call}
}

// MockCommunicatorStartCall wrap *gomock.Call
type MockCommunicatorStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommunicatorStartCall) Return(arg0 error) *MockCommunicatorStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommunicatorStartCall) Do(f func(context.Context, *packer.RemoteCmd) error) *MockCommunicatorStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommunicatorStartCall) DoAndReturn(f func(context.Context, *packer.RemoteCmd) error) *MockCommunicatorStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upload mocks base method.
func (m *MockCommunicator) Upload(arg0 string, arg1 io.Reader, arg2 *os.FileInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockCommunicatorMockRecorder) Upload(arg0, arg1, arg2 any) *MockCommunicatorUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockCommunicator)(nil).Upload), arg0, arg1, arg2)
	return &MockCommunicatorUploadCall{Call: call}
}

// MockCommunicatorUploadCall wrap *gomock.Call
type MockCommunicatorUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommunicatorUploadCall) Return(arg0 error) *MockCommunicatorUploadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommunicatorUploadCall) Do(f func(string, io.Reader, *os.FileInfo) error) *MockCommunicatorUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommunicatorUploadCall) DoAndReturn(f func(string, io.Reader, *os.FileInfo) error) *MockCommunicatorUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UploadDir mocks base method.
func (m *MockCommunicator) UploadDir(dst, src string, exclude []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDir", dst, src, exclude)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadDir indicates an expected call of UploadDir.
func (mr *MockCommunicatorMockRecorder) UploadDir(dst, src, exclude any) *MockCommunicatorUploadDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDir", reflect.TypeOf((*MockCommunicator)(nil).UploadDir), dst, src, exclude)
	return &MockCommunicatorUploadDirCall{Call: call}
}

// MockCommunicatorUploadDirCall wrap *gomock.Call
type MockCommunicatorUploadDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommunicatorUploadDirCall) Return(arg0 error) *MockCommunicatorUploadDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommunicatorUploadDirCall) Do(f func(string, string, []string) error) *MockCommunicatorUploadDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommunicatorUploadDirCall) DoAndReturn(f func(string, string, []string) error) *MockCommunicatorUploadDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
