// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mws-cloud-platform/packer-plugin-mws/post-processor/mws-export (interfaces: Driver)
//
// Generated by this command:
//
//	mockgen -typed -package=mock -destination=mock/driver_mock.go . Driver
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// CreateHMACKey mocks base method.
func (m *MockDriver) CreateHMACKey(ctx context.Context, serviceAccount, name string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHMACKey", ctx, serviceAccount, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateHMACKey indicates an expected call of CreateHMACKey.
func (mr *MockDriverMockRecorder) CreateHMACKey(ctx, serviceAccount, name any) *MockDriverCreateHMACKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHMACKey", reflect.TypeOf((*MockDriver)(nil).CreateHMACKey), ctx, serviceAccount, name)
	return &MockDriverCreateHMACKeyCall{Call: call}
}

// MockDriverCreateHMACKeyCall wrap *gomock.Call
type MockDriverCreateHMACKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDriverCreateHMACKeyCall) Return(accessKey, secretKey string, err error) *MockDriverCreateHMACKeyCall {
	c.Call = c.Call.Return(accessKey, secretKey, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDriverCreateHMACKeyCall) Do(f func(context.Context, string, string) (string, string, error)) *MockDriverCreateHMACKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDriverCreateHMACKeyCall) DoAndReturn(f func(context.Context, string, string) (string, string, error)) *MockDriverCreateHMACKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteHMACKey mocks base method.
func (m *MockDriver) DeleteHMACKey(ctx context.Context, serviceAccount, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHMACKey", ctx, serviceAccount, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHMACKey indicates an expected call of DeleteHMACKey.
func (mr *MockDriverMockRecorder) DeleteHMACKey(ctx, serviceAccount, name any) *MockDriverDeleteHMACKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHMACKey", reflect.TypeOf((*MockDriver)(nil).DeleteHMACKey), ctx, serviceAccount, name)
	return &MockDriverDeleteHMACKeyCall{Call: call}
}

// MockDriverDeleteHMACKeyCall wrap *gomock.Call
type MockDriverDeleteHMACKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDriverDeleteHMACKeyCall) Return(arg0 error) *MockDriverDeleteHMACKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDriverDeleteHMACKeyCall) Do(f func(context.Context, string, string) error) *MockDriverDeleteHMACKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDriverDeleteHMACKeyCall) DoAndReturn(f func(context.Context, string, string) error) *MockDriverDeleteHMACKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
