name: acceptance test

on:
  workflow_call:
    secrets:
      MWS_SERVICE_ACCOUNT_KEY:
        required: true
      MWS_HMAC_ACCESS_KEY:
        required: true  
      MWS_HMAC_SECRET_KEY:
        required: true
    inputs:
      MWS_TEST_PROJECT:
        required: true
        type: string
      MWS_TEST_OBJECT_STORAGE_BUCKET:
        required: true
        type: string
  workflow_dispatch:

jobs:
  acceptance-test:
    name: Acceptance Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26"
          cache: false
      - uses: hashicorp/setup-packer@ce93c3c08a6c2ff2275bf4b54ff0d9a75f6c9789 # v3.4.0
        with:
          version: "1.15.4"
      - name: Create service account key file
        env:
          MWS_SERVICE_ACCOUNT_KEY: ${{ secrets.MWS_SERVICE_ACCOUNT_KEY }}
        run: printf '%s' "$MWS_SERVICE_ACCOUNT_KEY" > service_account_authorized_key_packer_acctest.dms
      - name: Run acceptance test
        run: make testacc
        env:
          MWS_PROJECT: "${{ inputs.MWS_TEST_PROJECT || vars.MWS_TEST_PROJECT }}"
          MWS_SERVICE_ACCOUNT_AUTHORIZED_KEY_PATH: "${{ github.workspace }}/service_account_authorized_key_packer_acctest.dms"
          PKR_VAR_access_key: "${{ secrets.MWS_HMAC_ACCESS_KEY }}"
          PKR_VAR_secret_key: "${{ secrets.MWS_HMAC_SECRET_KEY }}"
          PKR_VAR_object_storage_bucket: "${{ inputs.MWS_TEST_OBJECT_STORAGE_BUCKET || vars.MWS_TEST_OBJECT_STORAGE_BUCKET }}"
      - name: Upload Test Logs Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: packer-acceptance-test-logs
          path: |
            builder/mws/packer_log_builder_example.txt
            post-processor/mws-export/packer_log_export_of_existing_image_example.txt
            post-processor/mws-export/packer_log_export_with_builder_example.txt
            post-processor/mws-import/packer_log_import_example.txt
          retention-days: 1
          if-no-files-found: ignore # packer deletes logs if tests completed successfully
      - name: Clean up service account key file
        run: rm -f service_account_authorized_key_packer_acctest.dms