name: acceptance test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  acceptance-test:
    name: Acceptance Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.26"
          cache: false
      - uses: hashicorp/setup-packer@v3
        with:
          version: "1.15.4"
      - name: Create service account key file
        env:
          MWS_SERVICE_ACCOUNT_KEY: ${{ secrets.MWS_SERVICE_ACCOUNT_KEY }}
        run: printf '%s' "$MWS_SERVICE_ACCOUNT_KEY" > service_account_authorized_key_packer_acctest.dms
      - name: Run acceptance test
        run: make testacc
        env:
          MWS_PROJECT: "${{ vars.MWS_TEST_PROJECT }}"
          MWS_SERVICE_ACCOUNT_AUTHORIZED_KEY_PATH: "${{ github.workspace }}/service_account_authorized_key_packer_acctest.dms"
          PKR_VAR_service_account: "${{ vars.MWS_TEST_SERVICE_ACCOUNT }}"
          PKR_VAR_object_storage_bucket: "${{ vars.MWS_TEST_OBJECT_STORAGE_BUCKET }}"
      - name: Clean up service account key file
        run: rm -f service_account_authorized_key_packer_acctest.dms